[font]
	size = 25.0
	normal = { family = "DroidSansMono Nerd Font", style = "Regular" }


[window]
padding = { x = 30, y = 35 }
startup_mode="Maximized"
decorations = "Buttonless"
#blur = true
opacity = 0.75

[terminal]
#hide_when_typing = true
osc52 = "CopyPaste"
