return {
	require("lazy").setup({
		require("lazy.startup"),
		require("lazy.vim-sleuth"),
		require("lazy.comment"),
		require("lazy.gitsigns"),
		require("lazy.telescope"),
		require("lazy.lspconfig"),
		require("lazy.conform"),
		require("lazy.autocomplete"),
		require("lazy.theme"),
		require("lazy.todo"),
		require("lazy.mini"),
		require("lazy.tree-sitter"),
		require("lazy.vim-helm"),
	}, {
		ui = {
			icons = {
				cmd = "⌘",
				config = "🛠",
				event = "📅",
				ft = "📂",
				init = "⚙",
				keys = "🗝",
				plugin = "🔌",
				runtime = "💻",
				require = "🌙",
				source = "📄",
				start = "🚀",
				task = "📌",
				lazy = "💤 ",
			},
		},
	}),
}
