alias zshconfig="vim ~/.zshrc && reload"
alias tmuxconfig="vim ~/.tmux.conf"
alias reload="source ~/.zshrc"
alias reload-tmux="tmux source-file ~/.tmux.conf"
alias vim="nvim"
alias py="python3"
alias config="vim ~/.config/"
alias ff=fastfetch
alias gs="git status"
