alias zshconfig="vim ~/.zshrc && reload"
alias tmuxconfig="vim ~/.tmux.conf"
alias reload="source ~/.zshrc"
alias reload-tmux="tmux source-file ~/.tmux.conf"
alias c="clear"
alias cl="clear && ls"
alias cla="clear && la"
alias vim="nvim"
alias py="python3"
alias cr="cargo r"
alias config="vim ~/.config/"
alias cd=z
alias ff=fastfetch
alias gs="git status"
